#########################################################################
# File Name: gitapply.sh
# Author: Cixi.Geng
# mail: cixi.geng@unisoc.com
# Created Time: 2019年08月29日 星期四 17时36分39秒
#########################################################################
#!/bin/bash
git apply 0001-Bug-1079807-BACKPORT-asm-generic-io.h-move-ioremap_n.patch
git apply 0002-Bug-1079807-sched-fix-compiling-error-on-min_cap_cpu.patch
git apply 0003-arch-um-enabled-running-kunit-from-User-Mode-Linux.patch
git apply 0004-kunit-test-adds-KUnit-a-basic-unit-testing-library-f.patch
git apply 0005-arch-um-added-shim-to-trap-to-allow-installing-a-fau.patch
git apply 0006-kunit-test-added-the-concept-of-assertions.patch
git apply 0007-kunit-test-added-concept-of-initcalls.patch
git apply 0008-kunit-test-added-concept-of-post-conditions.patch
git apply 0009-checkpatch-added-support-for-struct-MOCK-foo-syntax.patch
git apply 0010-kunit-mock-added-parameter-list-minipulation-macros.patch
git apply 0011-kunit-mock-added-basic-mock-infrastructure.patch
git apply 0012-kunit-mock-added-struct-param-matcher.patch
git apply 0013-kunit-mock-added-parameter-formatters.patch
git apply 0014-kunit-mock-implemented-nice-strict-and-naggy-mock-di.patch
git apply 0015-kunit-mock-add-ability-to-mock-functions-with-void-c.patch
git apply 0016-kunit-mock-added-support-for-arbitrary-function-mock.patch
git apply 0017-kunit-mock-added-the-concept-of-redirect-mockable-fu.patch
git apply 0018-kunit-mock-add-parameter-capturers.patch
git apply 0019-kunit-improved-sigsegv-stack-trace-printing.patch
git apply 0020-kunit-added-concept-of-platform-mocking.patch
git apply 0021-arch-um-added-stubs-for-mock-iomem-for-KUnit.patch
git apply 0022-Documentation-kunit-adds-complete-documentation-for-.patch
git apply 0023-kunit-added-Python-libraries-for-handing-KUnit-confi.patch
git apply 0024-kunit-added-KUnit-wrapper-script-and-simple-output-p.patch
git apply 0025-kunit.py-improved-output-from-python-wrapper.patch
git apply 0026-MAINTAINERS-add-entry-for-KUnit-the-unit-testing-fra.patch
git apply 0027-kunit-check-if-kernel-crashed-during-kunit.patch
git apply 0028-kunit-add-FAQ-to-documentation.patch
git apply 0029-kunit-remove-redundant-semicolon-from-macro.patch
git apply 0030-kunit-added-expectation-modifier-macros.patch
git apply 0031-kunit-add-parent-method-reference-to-expectation.patch
git apply 0032-kunit.py-functional-changes-for-testing.patch
git apply 0033-kunit-fix-up-some-style-and-syntax.patch
git apply 0034-kunit-added-InSequence-implementation.patch
git apply 0035-kunit-added-file-and-line-number-to-expectations.patch
git apply 0036-kunit-added-tests-for-Python-Script.patch
git apply 0037-kunit-add-locking-to-string-stream-operations.patch
git apply 0038-kunit-added-reference-counting-to-string-stream.patch
git apply 0039-kunit-Documentation-Dropped-bad-toctree-from-FAQ.patch
git apply 0040-kunit-added-missing-SPDX-headers.patch
git apply 0041-kunit-added-missing-newlines.patch
git apply 0042-kunit-Documentation-Fixed-non-ASCII-character.patch
git apply 0043-kunit-mock-swapped-out-fixed-width-integer-formatter.patch
git apply 0044-kunit-test-use-strlcat-in-string-stream.patch
git apply 0045-kunit-test-add-proper-CONFIGs-to-test-Kconfig.patch
git apply 0046-kunit-test-fixed-HAS_IOMEM-CONFIGs.patch
git apply 0047-kunit-Documentation-updated-documentation.patch
git apply 0048-kunit-Documentaiton-updated-download-link.patch
git apply 0049-kunit-mock-Retire-expectations-on-saturation-when-th.patch
git apply 0050-arch-um-add-linker-section-for-kunit-test-modules.patch
git apply 0051-kunit-test-create-single-dispatcher-for-kunit.patch
git apply 0052-init-main-add-KUnit-to-kernel-init.patch
git apply 0053-kunit-test-move-death-test-to-its-own-KUnit-config.patch
git apply 0054-kunit-mock-Add-three-Cardinality-expectation-macro-h.patch
git apply 0055-kunit.py-handle-timeout.patch
git apply 0056-kunit_tool-refactored-kunit_tool-for-adding-subcomma.patch
git apply 0057-kunit_tool-added-option-for-creating-KUnit-test-skel.patch
git apply 0058-kunit-test-fix-Makefile-CONFIG_-for-death-test.patch
git apply 0059-init-main-fix-ifdef-in-init-main.c.patch
git apply 0060-kunit_tool-add-support-to-print-only-sample-test.patch
git apply 0061-kunit_tool-update-to-support-kunit_watcher.patch
git apply 0062-kunit-print-the-mock-function-and-input-parameters-i.patch
git apply 0063-kunit-mock-print-the-mock-method-name-when-the-retur.patch
git apply 0064-kunit-mock-add-failed-expectation-to-output-message.patch
git apply 0065-kunit-test-add-test-managed-resource-tests.patch
git apply 0066-kunit.py-Exit-with-exit-code-of-1-when-all-tests-do-.patch
git apply 0067-Include-kunit.py-command-in-the-documentation.patch
git apply 0068-kunit-test-implement-formatters-for-error-codes.patch
git apply 0069-kunit-tool-fixed-test-broken-by-system.exit-1.patch
git apply 0070-kunit-test-improve-error-messages-for-invalid-kconfi.patch
git apply 0071-kunit-Documentation-fix-typo-and-includes-in-getting.patch
git apply 0072-kunit-tool-fixed-issue-introduced-by-improve-error-m.patch
git apply 0073-kunit-tool-fix-invalid-attribute-access-on-build-fai.patch
git apply 0074-kunit-tool-add-support-for-building-kernel-with-addi.patch
git apply 0075-kunit-tool-make-exit-status-non-zero-for-any-type-of.patch
git apply 0076-kunit-test-port-test-abort-support-to-x86.patch
git apply 0077-kunit-test-fix-incorrect-KUnit-log-prefix.patch
git apply 0078-Bug-1079807-arm64-kunit-porting-kunit-to-sprdlinux4..patch

