#!/bin/sh

PROJECTNAME=`git config --list |grep projectname|awk -F"=" '{print$NF}'`
#if [-e $PROJECTNAME ];then
#	PROJECTNAME=`git config --list |grep remote.origin.url |awk -F "unisoc.com/" '{print$NF}'`
#fi
BRANCH=`git branch -r |grep "\->" |awk -F"/" '{print$NF}'`
echo projectname=$PROJECTNAME
echo remote branch=$BRANCH
echo "git push ssh://cixi.geng1@review.source.spreadtrum.com:29418/$PROJECTNAME HEAD:refs/for/$BRANCH"
git push ssh://cixi.geng1@review.source.spreadtrum.com:29418/$PROJECTNAME HEAD:refs/for/$BRANCH

